### ISSUE TITLE
doesn't work well for PG 9.6.3+ version

### ISSUE THREAD

**Issue by harukat** [ossc-db/pg_dbms_stats#2]
It seems to me that pg_dbms_stats doesn't work well for PG 9.6.3+ version.
(after this patch https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=c33c42362 ?)

Both the original and dbms_stats' column histogram statistics are ignored
 when pg_dbms_stats.use_locked_stats = on;

example (with pg_dbms_stats-5c2b1d0 + PG9.6.5) :

```
db1=# CREATE TABLE t1 (id int primary key, v text);
CREATE TABLE
db1=# INSERT INTO t1 SELECT g, '1' || md5(g::text) FROM generate_series(1, 10000) as g;
INSERT 0 10000
db1=# VACUUM ANALYZE t1;
VACUUM

db1=# SELECT dbms_stats.clean_up_stats();
 clean_up_stats
----------------
(0 rows)

db1=# explain SELECT * FROM t1 WHERE v < '000';
                       QUERY PLAN
--------------------------------------------------------
 Seq Scan on t1  (cost=0.00..209.00 rows=5000 width=38)
   Filter: (v < '000'::text)
(2 rows)

db1=# SET pg_dbms_stats.use_locked_stats TO off;
SET

db1=# explain SELECT * FROM t1 WHERE v < '000';
                     QUERY PLAN
-----------------------------------------------------
 Seq Scan on t1  (cost=0.00..209.00 rows=1 width=38)
   Filter: (v < '000'::text)
(2 rows)

db1=# SELECT dbms_stats.lock_table_stats('t1');
 lock_table_stats
------------------
 t1
(1 row)

db1=# SET pg_dbms_stats.use_locked_stats TO on;
SET

db1=# explain SELECT * FROM t1 WHERE v < '000';
                       QUERY PLAN
--------------------------------------------------------
 Seq Scan on t1  (cost=0.00..209.00 rows=5000 width=38)
   Filter: (v < '000'::text)
(2 rows)
```

**Comment by horiguti** [comment]
Hello. Thank you for the clear report!

At Mon, 13 Nov 2017 00:32:16 +0000 (UTC), harukat <notifications@github.com> wrote in <ossc-db/pg_dbms_stats/issues/2@github.com>
> It seems to me that pg_dbms_stats doesn't work well for PG 9.6.3+ version.
> (after this patch https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=c33c42362 ?)

Fixed the problem and will soon released as 1.3.9 for PG9.2 to
PG10.

The problem hits on each PostgreSQL minor versions 9.2.21,
9.3.17, 9.4.12, 9.5.7, 9.6.3 and 10.0. pg_dbms_stats gets
affected on all the versions and this fix is back-patched back to
9.2.

pg_dbms_stats 1.3.9 compiled for the above minor versions or
later in a major version works for all minor versions of the
major version. (I only checked that between the two versions on
the border for each major version, e.g. 9.6.2 and 9.6.3.)

> Both the original and dbms_stats' column histogram statistics are ignored
>  when pg_dbms_stats.use_locked_stats = on;
> 
> example (with pg_dbms_stats-5c2b1d0 + PG9.6.5) :

The most serious problem was the lack to check if stored (locked)
statistics is actually works. Such test is added.

regards,
